name: stripe_native_card_field
description: A native flutter implementation of the elegant Stripe Card Field.
version: 0.0.1
repository: https://git.fosscat.com/n8r/stripe_native_card_field

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

